### PR TITLE
Updated elastics

### PR DESCRIPTION
**Pull request by engnadeau**

### CODE REVIEW

**Review by mdtusz — COMMENTED** [review]
May be good to add sourcing options for any/all raw materials. Can be a different PR though.

:dancer:

**Comment by nugvivi** [comment]
Assembly instructions should also be updated

**Comment by engnadeau** [comment]
@mdtusz done.

@nugvivi the assembly instructions already include the elastic (?)

**Review by mdtusz — APPROVED** [review]
:dancer:

**Pull request merged**
