### PR TITLE
Create DISCLAIMER.md

### PR DESCRIPTION
**Pull request by engnadeau**
Fixes https://aon3dhub.atlassian.net/browse/COVID-106 and https://aon3dhub.atlassian.net/browse/COVID-124

### CODE REVIEW

**Review by nugvivi — DISMISSED** [review]
@nnadeau I was going to add it at the bottom of the README. The link I posted on Jira is for the branch that this is in.
https://github.com/aon3d/covid-face-shield/commit/001b8f6716f016b884fe012d096d0fec488b0d5c
I have no preference for where this gets put though.

**Comment by engnadeau** [comment]
@nugvivi good idea for the README. I've typically seen disclaimers, licenses, codes of conduct, etc as separate files, which is why i made `DISCLAIMER.md` as its own thing. I added a link/reference to this file in the `README`

**Comment by matt-aon3d** [comment]
@nnadeau I've cc'd you on my email to the lawyer asking for recommendations as to whether it's a separate file or should be copied into all readable docs in the repository.

**Review by matt-aon3d — APPROVED** [review]

**Comment by engnadeau** [comment]
@matt-aon3d "all readable docs" would be a nightmare in terms of duplication

**Pull request merged**
